name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Package up a release
      run: zip -r ../badnest.zip hacs.json info.md custom_components
    - uses: ncipollo/release-action@v1
      with:
        artifact: ../badnest.zip
        artifactContentType: application/zip
        token: ${{ secrets.GITHUB_TOKEN }}
