name: Release uploader

on: release

jobs:
  upload_release:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1
      - name: Package up a release
        run: zip -r badnest.zip hacs.json info.md custom_components
      - uses: JasonEtco/upload-to-release@master
        with:
          args: badnest.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
